from typing import List
import jieba
import pypinyin

# PINYIN_DICT = {
#     "a": ["a"],
#     "ai": ["ai"],
#     "an": ["an"],
#     "ang": ["ɑŋ"],
#     "ao": ["aʌ"],
#     "ba": ["ba"],
#     "bai": ["bai"],
#     "ban": ["ban"],
#     "bang": ["bɑŋ"],
#     "bao": ["baʌ"],
#     # "be": ["be"], doesnt exist
#     "bei": ["bɛi"],
#     "ben": ["bœn"],
#     "beng": ["bɵŋ"],
#     "bi": ["bi"],
#     "bian": ["biɛn"],
#     "biao": ["biaʌ"],
#     "bie": ["bie"],
#     "bin": ["bin"],
#     "bing": ["bɨŋ"],
#     "bo": ["bo"],
#     "bu": ["bu"],
#     "ca": ["tsa"],
#     "cai": ["tsai"],
#     "can": ["tsan"],
#     "cang": ["tsɑŋ"],
#     "cao": ["tsaʌ"],
#     "ce": ["tsø"],
#     "cen": ["tsœn"],
#     "ceng": ["tsɵŋ"],
#     "cha": ["ʈʂa"],
#     "chai": ["ʈʂai"],
#     "chan": ["ʈʂan"],
#     "chang": ["ʈʂɑŋ"],
#     "chao": ["ʈʂaʌ"],
#     "che": ["ʈʂø"],
#     "chen": ["ʈʂœn"],
#     "cheng": ["ʈʂɵŋ"],
#     "chi": ["ʈʂʏ"],
#     "chong": ["ʈʂoŋ"],
#     "chou": ["ʈʂou"],
#     "chu": ["ʈʂu"],
#     "chua": ["ʈʂua"],
#     "chuai": ["ʈʂuai"],
#     "chuan": ["ʈʂuan"],
#     "chuang": ["ʈʂuɑŋ"],
#     "chui": ["ʈʂuei"],
#     "chun": ["ʈʂun"],
#     "chuo": ["ʈʂuo"],
#     "ci": ["tsɪ"],
#     "cong": ["tsoŋ"],
#     "cou": ["tsou"],
#     "cu": ["tsu"],
#     "cuan": ["tsuan"],
#     "cui": ["tsuei"],
#     "cun": ["tsun"],
#     "cuo": ["tsuo"],
#     "da": ["da"],
#     "dai": ["dai"],
#     "dan": ["dan"],
#     "dang": ["dɑŋ"],
#     "dao": ["daʌ"],
#     "de": ["dø"],
#     "dei": ["dei"],
#     # "den": ["dœn"],
#     "deng": ["dɵŋ"],
#     "di": ["di"],
#     "dia": ["dia"],
#     "dian": ["diɛn"],
#     "diao": ["diaʌ"],
#     "die": ["die"],
#     "ding": ["dɨŋ"],
#     "diu": ["dio"],
#     "dong": ["doŋ"],
#     "dou": ["dou"],
#     "du": ["du"],
#     "duan": ["duan"],
#     "dui": ["duei"],
#     "dun": ["dun"],
#     "duo": ["duo"],
#     "e": ["ø"],
#     "ei": ["ei"],
#     "en": ["œn"],
#     # "ng": ["œn"],
#     # "eng": ["ɵŋ"],
#     "er": ["er"],
#     "fa": ["fa"],
#     "fan": ["fan"],
#     "fang": ["fɑŋ"],
#     "fei": ["fei"],
#     "fen": ["fœn"],
#     "feng": ["fɵŋ"],
#     "fo": ["fo"],
#     "fou": ["fou"],
#     "fu": ["fu"],
#     "ga": ["ga"],
#     "gai": ["gai"],
#     "gan": ["gan"],
#     "gang": ["gɑŋ"],
#     "gao": ["gaʌ"],
#     "ge": ["gø"],
#     "gei": ["gei"],
#     "gen": ["gœn"],
#     "geng": ["gɵŋ"],
#     "gong": ["goŋ"],
#     "gou": ["gou"],
#     "gu": ["gu"],
#     "gua": ["gua"],
#     "guai": ["guai"],
#     "guan": ["guan"],
#     "guang": ["guɑŋ"],
#     "gui": ["guei"],
#     "gun": ["gun"],
#     "guo": ["guo"],
#     "ha": ["xa"],
#     "hai": ["xai"],
#     "han": ["xan"],
#     "hang": ["xɑŋ"],
#     "hao": ["xaʌ"],
#     "he": ["xø"],
#     "hei": ["xei"],
#     "hen": ["xœn"],
#     "heng": ["xɵŋ"],
#     "hong": ["xoŋ"],
#     "hou": ["xou"],
#     "hu": ["xu"],
#     "hua": ["xua"],
#     "huai": ["xuai"],
#     "huan": ["xuan"],
#     "huang": ["xuɑŋ"],
#     "hui": ["xuei"],
#     "hun": ["xun"],
#     "huo": ["xuo"],
#     "ji": ["dʑi"],
#     "jia": ["dʑia"],
#     "jian": ["dʑiɛn"],
#     "jiang": ["dʑiɑŋ"],
#     "jiao": ["dʑiaʌ"],
#     "jie": ["dʑie"],
#     "jin": ["dʑin"],
#     "jing": ["dʑɨŋ"],
#     "jiong": ["dʑioŋ"],
#     "jiu": ["dʑio"],
#     "ju": ["dʑy"],
#     "juan": ["dʑyɛn"],
#     "jue": ["dʑye"],
#     "jun": ["dʑyn"],
#     "ka": ["ka"],
#     "kai": ["kai"],
#     "kan": ["kan"],
#     "kang": ["kɑŋ"],
#     "kao": ["kaʌ"],
#     "ke": ["kø"],
#     "kei": ["kei"],
#     "ken": ["kœn"],
#     "keng": ["kɵŋ"],
#     "kong": ["koŋ"],
#     "kou": ["kou"],
#     "ku": ["ku"],
#     "kua": ["kua"],
#     "kuai": ["kuai"],
#     "kuan": ["kuan"],
#     "kuang": ["kuɑŋ"],
#     "kui": ["kuei"],
#     "kun": ["kun"],
#     "kuo": ["kuo"],
#     "la": ["la"],
#     "lai": ["lai"],
#     "lan": ["lan"],
#     "lang": ["lɑŋ"],
#     "lao": ["laʌ"],
#     "le": ["lø"],
#     "lei": ["lei"],
#     "leng": ["lɵŋ"],
#     "li": ["li"],
#     "lia": ["lia"],
#     "lian": ["liɛn"],
#     "liang": ["liɑŋ"],
#     "liao": ["liaʌ"],
#     "lie": ["lie"],
#     "lin": ["lin"],
#     "ling": ["lɨŋ"],
#     "liu": ["lio"],
#     "lo": ["lo"],
#     "long": ["loŋ"],
#     "lou": ["lou"],
#     "lu": ["lu"],
#     "lv": ["ly"],
#     "luan": ["luan"],
#     "lve": ["lye"],
#     "lue": ["lue"],
#     "lun": ["lun"],
#     "luo": ["luo"],
#     "ma": ["ma"],
#     "mai": ["mai"],
#     "man": ["man"],
#     "mang": ["mɑŋ"],
#     "mao": ["maʌ"],
#     "me": ["mø"],
#     "mei": ["mei"],
#     "men": ["mœn"],
#     "meng": ["mɵŋ"],
#     "mi": ["mi"],
#     "mian": ["miɛn"],
#     "miao": ["miaʌ"],
#     "mie": ["mie"],
#     "min": ["min"],
#     "ming": ["mɨŋ"],
#     "miu": ["mio"],
#     "mo": ["mo"],
#     "mou": ["mou"],
#     "mu": ["mu"],
#     "na": ["na"],
#     "nai": ["nai"],
#     "nan": ["nan"],
#     "nang": ["nɑŋ"],
#     "nao": ["naʌ"],
#     "ne": ["nø"],
#     "nei": ["nei"],
#     "nen": ["nœn"],
#     "neng": ["nɵŋ"],
#     "ni": ["ni"],
#     "nia": ["nia"],
#     "nian": ["niɛn"],
#     "niang": ["niɑŋ"],
#     "niao": ["niaʌ"],
#     "nie": ["nie"],
#     "nin": ["nin"],
#     "ning": ["nɨŋ"],
#     "niu": ["nio"],
#     "nong": ["noŋ"],
#     "nou": ["nou"],
#     "nu": ["nu"],
#     "nv": ["ny"],
#     "nuan": ["nuan"],
#     "nve": ["nye"],
#     "nue": ["nye"],
#     "nuo": ["nuo"],
#     "o": ["o"],
#     "ou": ["ou"],
#     "pa": ["pa"],
#     "pai": ["pai"],
#     "pan": ["pan"],
#     "pang": ["pɑŋ"],
#     "pao": ["paʌ"],
#     "pe": ["pø"],
#     "pei": ["pei"],
#     "pen": ["pœn"],
#     "peng": ["pɵŋ"],
#     "pi": ["pi"],
#     "pian": ["piɛn"],
#     "piao": ["piaʌ"],
#     "pie": ["pie"],
#     "pin": ["pin"],
#     "ping": ["pɨŋ"],
#     "po": ["po"],
#     "pou": ["pou"],
#     "pu": ["pu"],
#     "qi": ["tɕi"],
#     "qia": ["tɕia"],
#     "qian": ["tɕiɛn"],
#     "qiang": ["tɕiɑŋ"],
#     "qiao": ["tɕiaʌ"],
#     "qie": ["tɕie"],
#     "qin": ["tɕin"],
#     "qing": ["tɕɨŋ"],
#     "qiong": ["tɕioŋ"],
#     "qiu": ["tɕio"],
#     "qu": ["tɕy"],
#     "quan": ["tɕyɛn"],
#     "que": ["tɕye"],
#     "qun": ["tɕyn"],
#     "ran": ["ʐan"],
#     "rang": ["ʐɑŋ"],
#     "rao": ["ʐaʌ"],
#     "re": ["ʐø"],
#     "ren": ["ʐœn"],
#     "reng": ["ʐɵŋ"],
#     "ri": ["ʐʏ"],
#     "rong": ["ʐoŋ"],
#     "rou": ["ʐou"],
#     "ru": ["ʐu"],
#     "rua": ["ʐua"],
#     "ruan": ["ʐuan"],
#     "rui": ["ʐuei"],
#     "run": ["ʐun"],
#     "ruo": ["ʐuo"],
#     "sa": ["sa"],
#     "sai": ["sai"],
#     "san": ["san"],
#     "sang": ["sɑŋ"],
#     "sao": ["saʌ"],
#     "se": ["sø"],
#     "sen": ["sœn"],
#     "seng": ["sɵŋ"],
#     "sha": ["ʂa"],
#     "shai": ["ʂai"],
#     "shan": ["ʂan"],
#     "shang": ["ʂɑŋ"],
#     "shao": ["ʂaʌ"],
#     "she": ["ʂø"],
#     "shei": ["ʂei"],
#     "shen": ["ʂœn"],
#     "sheng": ["ʂɵŋ"],
#     "shi": ["ʂʏ"],
#     "shou": ["ʂou"],
#     "shu": ["ʂu"],
#     "shua": ["ʂua"],
#     "shuai": ["ʂuai"],
#     "shuan": ["ʂuan"],
#     "shuang": ["ʂuɑŋ"],
#     "shui": ["ʂuei"],
#     "shun": ["ʂun"],
#     "shuo": ["ʂuo"],
#     "si": ["sɪ"],
#     "song": ["soŋ"],
#     "sou": ["sou"],
#     "su": ["su"],
#     "suan": ["suan"],
#     "sui": ["suei"],
#     "sun": ["sun"],
#     "suo": ["suo"],
#     "ta": ["ta"],
#     "tai": ["tai"],
#     "tan": ["tan"],
#     "tang": ["tɑŋ"],
#     "tao": ["taʌ"],
#     "te": ["tø"],
#     "tei": ["tei"],
#     "teng": ["tɵŋ"],
#     "ti": ["ti"],
#     "tian": ["tiɛn"],
#     "tiao": ["tiaʌ"],
#     "tie": ["tie"],
#     "ting": ["tɨŋ"],
#     "tong": ["toŋ"],
#     "tou": ["tou"],
#     "tu": ["tu"],
#     "tuan": ["tuan"],
#     "tui": ["tuei"],
#     "tun": ["tun"],
#     "tuo": ["tuo"],
#     "wa": ["wa"],
#     "wai": ["wai"],
#     "wan": ["wan"],
#     "wang": ["wɑŋ"],
#     "wei": ["wei"],
#     "wen": ["wœn"],
#     "weng": ["wɵŋ"],
#     "wo": ["wo"],
#     "wu": ["wu"],
#     "xi": ["ɕi"],
#     "xia": ["ɕia"],
#     "xian": ["ɕiɛn"],
#     "xiang": ["ɕiɑŋ"],
#     "xiao": ["ɕiaʌ"],
#     "xie": ["ɕie"],
#     "xin": ["ɕin"],
#     "xing": ["ɕɨŋ"],
#     "xiong": ["ɕioŋ"],
#     "xiu": ["ɕio"],
#     "xu": ["ɕy"],
#     "xuan": ["ɕyɛn"],
#     "xue": ["ɕye"],
#     "xun": ["ɕyn"],
#     "ya": ["ia"],
#     "yan": ["iɛn"],
#     "yang": ["iɑŋ"],
#     "yao": ["iaʌ"],
#     "ye": ["ie"],
#     "yi": ["i"],
#     "yin": ["in"],
#     "ying": ["ɨŋ"],
#     "yo": ["io"],
#     "yong": ["ioŋ"],
#     "you": ["io"],
#     "yu": ["y"],
#     "yuan": ["yɛn"],
#     "yue": ["ye"],
#     "yun": ["yn"],
#     "za": ["dza"],
#     "zai": ["dzai"],
#     "zan": ["dzan"],
#     "zang": ["dzɑŋ"],
#     "zao": ["dzaʌ"],
#     "ze": ["dzø"],
#     "zei": ["dzei"],
#     "zen": ["dzœn"],
#     "zeng": ["dzɵŋ"],
#     "zha": ["dʒa"],
#     "zhai": ["dʒai"],
#     "zhan": ["dʒan"],
#     "zhang": ["dʒɑŋ"],
#     "zhao": ["dʒaʌ"],
#     "zhe": ["dʒø"],
#     # "zhei": ["dʒei"], it doesn't exist
#     "zhen": ["dʒœn"],
#     "zheng": ["dʒɵŋ"],
#     "zhi": ["dʒʏ"],
#     "zhong": ["dʒoŋ"],
#     "zhou": ["dʒou"],
#     "zhu": ["dʒu"],
#     "zhua": ["dʒua"],
#     "zhuai": ["dʒuai"],
#     "zhuan": ["dʒuan"],
#     "zhuang": ["dʒuɑŋ"],
#     "zhui": ["dʒuei"],
#     "zhun": ["dʒun"],
#     "zhuo": ["dʒuo"],
#     "zi": ["dzɪ"],
#     "zong": ["dzoŋ"],
#     "zou": ["dzou"],
#     "zu": ["dzu"],
#     "zuan": ["dzuan"],
#     "zui": ["dzuei"],
#     "zun": ["dzun"],
#     "zuo": ["dzuo"],
# }

PINYIN_DICT = {
    'ba': 'pˈa',
    'bo': 'pˈwɔ',
    'bai': 'pˈaɪ',
    'bei': 'pˈeɪ',
    'bao': 'pˈaʊ',
    'ban': 'pˈan',
    'ben': 'pˈən',
    'bang': 'pˈɑŋ',
    'beng': 'pˈəŋ',
    'bi': 'pˈi',
    'biao': 'pˈjaʊ',
    'bie': 'pˈjɛ',
    'bian': 'pˈjɛn',
    'bin': 'pˈin',
    'bing': 'pˈiŋ',
    'bu': 'pˈu',
    'pa': 'pʰˈa',
    'po': 'pʰˈwɔ',
    'pai': 'pʰˈaɪ',
    'pei': 'pʰˈeɪ',
    'pao': 'pʰˈaʊ',
    'pou': 'pʰˈoʊ',
    'pan': 'pʰˈan',
    'pen': 'pʰˈən',
    'pang': 'pʰˈɑŋ',
    'peng': 'pʰˈəŋ',
    'pi': 'pʰˈi',
    'piao': 'pʰˈjaʊ',
    'pie': 'pʰˈjɛ',
    'pian': 'pʰˈjɛn',
    'pin': 'pʰˈin',
    'ping': 'pʰˈiŋ',
    'pu': 'pʰˈu',
    'ma': 'mˈa',
    'me': 'mˈɤ',
    'mo': 'mˈwɔ',
    'mai': 'mˈaɪ',
    'mei': 'mˈeɪ',
    'mao': 'mˈaʊ',
    'mou': 'mˈoʊ',
    'man': 'mˈan',
    'men': 'mˈən',
    'mang': 'mˈɑŋ',
    'meng': 'mˈəŋ',
    'mi': 'mˈi',
    'miao': 'mˈjaʊ',
    'mie': 'mˈjɛ',
    'miu': 'mˈju',
    'mian': 'mˈjɛn',
    'min': 'mˈin',
    'ming': 'mˈiŋ',
    'mu': 'mˈu',
    'fa': 'fˈa',
    'fo': 'fˈwɔ',
    'fei': 'fˈeɪ',
    'fou': 'fˈoʊ',
    'fan': 'fˈan',
    'fen': 'fˈən',
    'fang': 'fˈɑŋ',
    'feng': 'fˈəŋ',
    'fu': 'fˈu',
    'da': 'tˈa',
    'de': 'tˈɤ',
    'dai': 'tˈaɪ',
    'dei': 'tˈeɪ',
    'dao': 'tˈaʊ',
    'dou': 'tˈoʊ',
    'dan': 'tˈan',
    'dang': 'tˈɑŋ',
    'deng': 'tˈəŋ',
    'dong': 'tˈʊŋ',
    'di': 'tˈi',
    'diao': 'tˈjaʊ',
    'die': 'tˈjɛ',
    'diu': 'tˈjoʊ',
    'dian': 'tˈjɛn',
    'ding': 'tˈiŋ',
    'du': 'tˈu',
    'duo': 'tˈwɔ',
    'dui': 'tˈweɪ',
    'duan': 'tˈwan',
    'dun': 'tˈwən',
    'ta': 'tʰˈa',
    'te': 'tʰˈɤ',
    'tai': 'tʰˈaɪ',
    'tao': 'tʰˈaʊ',
    'tou': 'tʰˈoʊ',
    'tan': 'tʰˈan',
    'tang': 'tʰˈɑŋ',
    'teng': 'tʰˈəŋ',
    'tong': 'tʰˈʊŋ',
    'ti': 'tʰˈi',
    'tiao': 'tʰˈjaʊ',
    'tie': 'tʰˈjɛ',
    'tian': 'tʰˈjɛn',
    'ting': 'tʰˈiŋ',
    'tu': 'tʰˈu',
    'tuo': 'tʰˈwɔ',
    'tui': 'tʰˈweɪ',
    'tuan': 'tʰˈwan',
    'tun': 'tʰˈwən',
    'na': 'nˈa',
    'ne': 'nˈɤ',
    'nai': 'nˈaɪ',
    'nei': 'nˈeɪ',
    'nao': 'nˈaʊ',
    'nou': 'nˈoʊ',
    'nan': 'nˈan',
    'nen': 'nˈən',
    'nang': 'nˈɑŋ',
    'neng': 'nˈəŋ',
    'nong': 'nˈʊŋ',
    'ni': 'nˈi',
    'niao': 'nˈjaʊ',
    'nie': 'nˈjɛ',
    'niu': 'nˈjoʊ',
    'nian': 'nˈjɛn',
    'nin': 'nˈin',
    'niang': 'nˈiɑŋ',
    'ning': 'nˈiŋ',
    'nu': 'nˈu',
    'nuo': 'nˈwɔ',
    'nuan': 'nˈwan',
    'nü': 'nˈy',
    'nüe': 'nˈyɛ',
    'la': 'lˈa',
    'le': 'lˈɤ',
    'lai': 'lˈaɪ',
    'lei': 'lˈeɪ',
    'lao': 'lˈaʊ',
    'lou': 'lˈoʊ',
    'lan': 'lˈan',
    'lang': 'lˈɑŋ',
    'leng': 'lˈəŋ',
    'long': 'lˈʊŋ',
    'li': 'lˈi',
    'lia': 'lˈja',
    'liao': 'lˈjaʊ',
    'lie': 'lˈjɛ',
    'liu': 'lˈjoʊ',
    'lian': 'lˈjɛn',
    'lin': 'lˈin',
    'liang': 'lˈiɑŋ',
    'ling': 'lˈiŋ',
    'lu': 'lˈu',
    'luo': 'lˈwɔ',
    'luan': 'lˈwan',
    'lun': 'lˈwən',
    'lü': 'lˈy',
    'lüe': 'lˈyɛ',
    'za': 'tsˈa',
    'ze': 'tsˈɤ',
    'zi': 'tsˈɹ',
    'zai': 'tsˈaɪ',
    'zei': 'tsˈeɪ',
    'zao': 'tsˈaʊ',
    'zou': 'tsˈoʊ',
    'zan': 'tsˈan',
    'zen': 'tsˈən',
    'zang': 'tsˈɑŋ',
    'zeng': 'tsˈəŋ',
    'zong': 'tsˈʊŋ',
    'zu': 'tsˈu',
    'zuo': 'tsˈwɔ',
    'zui': 'tsˈweɪ',
    'zuan': 'tsˈwan',
    'zun': 'tsˈwən',
    'ca': 'tsʰˈa',
    'ce': 'tsʰˈɤ',
    'ci': 'tsʰˈɹ',
    'cai': 'tsʰˈaɪ',
    'cao': 'tsʰˈaʊ',
    'cou': 'tsʰˈoʊ',
    'can': 'tsʰˈan',
    'cen': 'tsʰˈən',
    'cang': 'tsʰˈɑŋ',
    'ceng': 'tsʰˈəŋ',
    'cong': 'tsʰˈʊŋ',
    'cu': 'tsʰˈu',
    'cuo': 'tsʰˈwɔ',
    'cui': 'tsʰˈweɪ',
    'cuan': 'tsʰˈwan',
    'cun': 'tsʰˈwən',
    'sa': 'sˈa',
    'se': 'sˈɤ',
    'si': 'sˈɹ',
    'sai': 'sˈaɪ',
    'sao': 'sˈaʊ',
    'sou': 'sˈoʊ',
    'san': 'sˈan',
    'sen': 'sˈən',
    'sang': 'sˈɑŋ',
    'seng': 'sˈeŋ',
    'song': 'sˈʊŋ',
    'su': 'sˈu',
    'suo': 'sˈwɔ',
    'sui': 'sˈweɪ',
    'suan': 'sˈwan',
    'sun': 'sˈwən',
    'zha': 'ʈʂˈa',
    'zhe': 'ʈʂˈɤ',
    'zhi': 'ʈʂˈʐ',
    'zhai': 'ʈʂˈaɪ',
    'zhei': 'ʈʂˈeɪ',
    'zhao': 'ʈʂˈaʊ',
    'zhou': 'ʈʂˈoʊ',
    'zhan': 'ʈʂˈan',
    'zhen': 'ʈʂˈən',
    'zhang': 'ʈʂˈɑŋ',
    'zheng': 'ʈʂˈəŋ',
    'zhong': 'ʈʂˈʊŋ',
    'zhu': 'ʈʂˈu',
    'zhua': 'ʈʂˈwa',
    'zhuo': 'ʈʂˈwɔ',
    'zhuai': 'ʈʂˈwaɪ',
    'zhui': 'ʈʂˈweɪ',
    'zhuan': 'ʈʂˈwan',
    'zhun': 'ʈʂˈwən',
    'zhuang': 'ʈʂˈwɑŋ',
    'cha': 'ʈʂʰˈa',
    'che': 'ʈʂʰˈɤ',
    'chi': 'ʈʂʰˈʐ',
    'chai': 'ʈʂʰˈaɪ',
    'chao': 'ʈʂʰˈaʊ',
    'chou': 'ʈʂʰˈoʊ',
    'chan': 'ʈʂʰˈan',
    'chen': 'ʈʂʰˈən',
    'chang': 'ʈʂʰˈɑŋ',
    'cheng': 'ʈʂʰˈəŋ',
    'chong': 'ʈʂʰˈʊŋ',
    'chu': 'ʈʂʰˈu',
    'chua': 'ʈʂʰˈwa',
    'chuo': 'ʈʂʰˈwɔ',
    'chuai': 'ʈʂʰˈwaɪ',
    'chui': 'ʈʂʰˈweɪ',
    'chuan': 'ʈʂʰˈwan',
    'chun': 'ʈʂʰˈwən',
    'chuang': 'ʈʂʰˈwɑŋ',
    'sha': 'ʂˈa',
    'she': 'ʂˈɤ',
    'shi': 'ʂˈʐ',
    'shai': 'ʂˈaɪ',
    'shei': 'ʂˈeɪ',
    'shao': 'ʂˈaʊ',
    'shou': 'ʂˈoʊ',
    'shan': 'ʂˈan',
    'shen': 'ʂˈən',
    'shang': 'ʂˈɑŋ',
    'sheng': 'ʂˈəŋ',
    'shu': 'ʂˈu',
    'shua': 'ʂˈwa',
    'shuo': 'ʂˈwɔ',
    'shuai': 'ʂˈwaɪ',
    'shui': 'ʂˈweɪ',
    'shuan': 'ʂˈwan',
    'shun': 'ʂˈwən',
    'shuang': 'ʂˈwɑŋ',
    're': 'ɹˈɤ',
    'ri': 'ɹˈʐ',
    'rao': 'ɹˈaʊ',
    'rou': 'ɹˈoʊ',
    'ran': 'ɹˈan',
    'ren': 'ɹˈən',
    'rang': 'ɹˈɑŋ',
    'reng': 'ɹˈəŋ',
    'rong': 'ɹˈʊŋ',
    'ru': 'ɹˈu',
    'ruo': 'ɹˈwɔ',
    'rui': 'ɹˈweɪ',
    'ruan': 'ɹˈwan',
    'run': 'ɹˈwən',
    'ji': 'tɕˈi',
    'jia': 'tɕˈja',
    'jiao': 'tɕˈjaʊ',
    'jie': 'tɕˈjɛ',
    'jiu': 'tɕˈjoʊ',
    'jian': 'tɕˈjɛn',
    'jin': 'tɕˈin',
    'jiang': 'tɕˈiɑŋ',
    'jing': 'tɕˈiŋ',
    'jiong': 'tɕˈjʊŋ',
    'ju': 'tɕˈy',
    'jue': 'tɕˈyɛ',
    'juan': 'tɕˈyɛn',
    'jun': 'tɕˈyn',
    'qi': 'tɕʰˈi',
    'qia': 'tɕʰˈja',
    'qiao': 'tɕʰˈjaʊ',
    'qie': 'tɕʰˈjɛ',
    'qiu': 'tɕʰˈjoʊ',
    'qian': 'tɕʰˈjɛn',
    'qin': 'tɕʰˈin',
    'qiang': 'tɕʰˈjɑŋ',
    'qing': 'tɕʰˈiŋ',
    'qiong': 'tɕʰˈjʊŋ',
    'qu': 'tɕʰˈy',
    'que': 'tɕʰˈyɛ',
    'quan': 'tɕʰˈyɛn',
    'qun': 'tɕʰˈyn',
    'xi': 'ɕˈi',
    'xia': 'ɕˈja',
    'xiao': 'ɕˈjaʊ',
    'xie': 'ɕˈjɛ',
    'xiu': 'ɕˈjoʊ',
    'xian': 'ɕˈjɛn',
    'xin': 'ɕˈin',
    'xiang': 'ɕˈiɑŋ',
    'xing': 'ɕˈiŋ',
    'xiong': 'ɕˈjʊŋ',
    'xu': 'ɕˈy',
    'xue': 'ɕˈyɛ',
    'xuan': 'ɕˈyɛn',
    'xun': 'ɕˈyn',
    'ga': 'kˈa',
    'ge': 'kˈɤ',
    'gai': 'kˈaɪ',
    'gei': 'kˈeɪ',
    'gao': 'kˈaʊ',
    'gou': 'kˈoʊ',
    'gan': 'kˈan',
    'gen': 'kˈən',
    'gang': 'kˈɑŋ',
    'geng': 'kˈəŋ',
    'gong': 'kˈʊŋ',
    'gu': 'kˈu',
    'gua': 'kˈwa',
    'guo': 'kˈwɔ',
    'guai': 'kˈwaɪ',
    'gui': 'kˈweɪ',
    'guan': 'kˈwan',
    'gun': 'kˈwən',
    'guang': 'kˈwɑŋ',
    'ka': 'kʰˈa',
    'ke': 'kʰˈɤ',
    'kai': 'kʰˈaɪ',
    'kei': 'kʰˈeɪ',
    'kao': 'kʰˈaʊ',
    'kou': 'kʰˈoʊ',
    'kan': 'kʰˈan',
    'ken': 'kʰˈən',
    'kang': 'kʰˈɑŋ',
    'keng': 'kʰˈəŋ',
    'kong': 'kʰˈʊŋ',
    'ku': 'kʰˈu',
    'kua': 'kʰˈwa',
    'kuo': 'kʰˈwɔ',
    'kuai': 'kʰˈwaɪ',
    'kui': 'kʰˈweɪ',
    'kuan': 'kʰˈwan',
    'kun': 'kʰˈwən',
    'kuang': 'kʰˈwɑŋ',
    'ha': 'xˈa',
    'he': 'xˈɤ',
    'hai': 'xˈaɪ',
    'hei': 'xˈeɪ',
    'hao': 'xˈaʊ',
    'hou': 'xˈoʊ',
    'han': 'xˈan',
    'hen': 'xˈən',
    'hang': 'xˈɑŋ',
    'heng': 'xˈəŋ',
    'hong': 'xˈʊŋ',
    'hu': 'xˈu',
    'hua': 'xˈwa',
    'huo': 'xˈwɔ',
    'huai': 'xˈwaɪ',
    'hui': 'xˈweɪ',
    'huan': 'xˈwan',
    'hun': 'xˈwən',
    'huang': 'xˈwɑŋ',
    'a': 'ˈa',
    'o': 'ˈo',
    'e': 'ˈɤ',
    'er': 'ˈɚ',
    'ai': 'ˈaɪ',
    'ei': 'ˈeɪ',
    'ao': 'ˈaʊ',
    'ou': 'ˈoʊ',
    'an': 'ˈan',
    'en': 'ˈən',
    'ang': 'ˈɑŋ',
    'eng': 'ˈəŋ',
    'yi': 'ˈi',
    'ya': 'jˈa',
    'yao': 'jˈaʊ',
    'ye': 'jˈɛ',
    'you': 'jˈoʊ',
    'yan': 'jˈɛn',
    'yin': 'ˈin',
    'yang': 'jˈɑŋ',
    'ying': 'ˈiŋ',
    'yong': 'ˈjʊŋ',
    'wu': 'ˈu',
    'wa': 'wˈa',
    'wo': 'wˈɔ',
    'wai': 'wˈaɪ',
    'wei': 'wˈeɪ',
    'wan': 'wˈan',
    'wen': 'wˈən',
    'wang': 'wˈɑŋ',
    'weng': 'wˈəŋ',
    'yu': 'ˈy',
    'yue': 'ɥˈɛ',
    'yuan': 'ɥˈɛn',
    'yun': 'ɥˈn',
    'hair': 'xˈaɹ',
    'dianr': 'tˈjaɹ',
    'wanr': 'wˈaɹ',
    'nar': 'nˈaɹ',
    'yanr': 'jˈaɹ',
    'huor': 'xˈwɔɹ',
    'duanr': 'tˈwaɹ',
    'lir': 'lˈjɚ',
    'huir': 'xˈwjɚ',
    'zher': 'ʈʂˈɚ',
    'dour': 'xˈɔɹ',
    'weir': 'wˈɚ',
    'kuair': 'kʰˈwaɹ',
    'guanr': 'gˈwɐʴ',
    'shir': 'ʂˈɚ',
    'yuanr': 'ɥˈɚ',
    'jianr': 'tɕˈjɚ',
    'her': 'xˈɚ',
    'jiar': 'tɕˈjaɹ',
    '': '',
    'bor': 'pˈwɔɹ',
    'xir': 'ɕˈɚ',
    'bianr': 'pˈjɚ',
    'fenr': 'fˈɚ',
    'wenr': 'wˈɚ',
    'der': 'tˈɚ',
    'por': 'pʰˈwɔɹ',
    'yuer': 'ɥˈɚ',
    'mingr': 'mˈjɚ',
    'char': 'ʈʂʰˈaɹ',
    'xingr': 'ɕˈjɚ',
    'zhour': 'ʈʂˈoʊɹ',
    'shour': 'ʂˈoʊɹ',
    'ter': 'tʰˈɚ',
    'yingr': 'ˈjɚ',
    'paor': 'pʰˈaɹ',
    'fangr': 'fˈɑɹ',
    'jingr': 'tɕˈjɚ',
    'shur': 'ʂˈuɹ',
    'qunr': 'tɕʰˈyɹ',
    'hur': 'xˈuɹ',
    'miaor': 'mˈjaʊɹ',
    'biaor': 'pˈjaʊɹ',
    'zhengr': 'ʈʂˈɚ',
    'gour': 'kˈoʊɹ',
    'pair': 'pʰˈaɹ',
    'renr': 'ɹˈɚ',
    'gaor': 'kˈaʊɹ',
    'lo': 'lˈoʊ',
    'tuir': 'tʰˈwɚ',
    'huanr': 'xˈwaɹ',
    'genr': 'kˈɚ',
    'nvr': 'nˈyɹ',
    'qianr': 'tɕʰˈjɚ',
    'hangr': 'xˈɑɹ',
    'chenr': 'ʈʂʰˈɚ',
    'den': 'tˈɚ',
    'lar': 'lˈaɹ',
    'niur': 'nˈjoʊɹ',
    'liur': 'lˈjoʊɹ',
    'tunr': 'tʰˈwɚ',
    'lunr': 'lˈwɚ',
    'tour': 'tʰˈoʊɹ',
    'hour': 'xˈoʊɹ',
    'tianr': 'tʰˈjɚ',
    'mianr': 'mˈjɚ',
    'mar': 'mˈaɹ',
    'pianr': 'pʰˈjɚ',
    'maor': 'mˈaʊɹ',
    'cair': 'tsʰˈɚ',
    'far': 'fˈaɹ',
    'shuor': 'ʂˈwɔɹ',
    'kanr': 'kʰˈaɹ',
    'banr': 'pˈaɹ',
    'ger': 'kˈɚ',
    'sher': 'ʂˈɚ',
    'gunr': 'kˈwɚ',
    'beir': 'pˈɚ',
    'chuanr': 'ʈʂʰˈwɚ',
    'bar': 'pˈaɹ',
    'cunr': 'tsʰˈwɚ',
    'tiaor': 'tʰˈjaʊɹ',
    'shuar': 'ʂˈwaɹ',
    'tur': 'tʰˈuɹ',
    'zhaor': 'ʈʂˈaʊɹ',
    'cher': 'ʈʂʰˈɚ',
    'menr': 'mˈɚ',
    'qingr': 'tɕʰˈjɚ',
    'shanr': 'ʂˈaɹ',
    'mor': 'mˈwɔɹ',
    'zhur': 'ʈʂˈuɹ',
    'wangr': 'wˈɑɹ',
    'zhunr': 'ʈʂˈwɚ',
    'zhir': 'ʈʂˈɚ',
    'haor': 'xˈaʊɹ',
    'shuir': 'ʂˈwɚ',
    'guor': 'kˈwɔɹ',
    'zaor': 'tsˈaʊɹ',
    'juanr': 'tɕˈyɚ',
    'jiar': 'tɕˈjaɹ',
    'xiaor': 'ɕˈjaʊɹ',
    'suor': 'sˈwɔɹ',
    'shaor': 'ʂˈaʊɹ',
    'yir': 'ˈɚ',
    'dir': 'tˈɚ',
    'ganr': 'kˈaɹ',
    'duir': 'tˈwɚ',
    'taor': 'tʰˈaʊɹ',
    'lianr': 'lˈjɚ',
    'benr': 'pˈɚ',
    'fanr': 'fˈaɹ',
    'xuer': 'ɕˈyɚ',
    'pur': 'pʰˈuɹ',
    'jinr': 'tɕˈɚ',
    'kour': 'kʰˈoʊɹ',
    'ker': 'kʰˈɚ',
    'mur': 'mˈuɹ',
    'liaor': 'lˈjaʊɹ',
    'juer': 'tɕˈyɚ',
    'your': 'jˈoʊɹ',
    'xianr': 'ɕˈjɚ',
    'quanr': 'tɕʰˈyɚ',
    'yo': 'jˈoʊ',
    'sanr': 'sˈaɹ',
    'zhuor': 'ʈʂˈwɔɹ',
    'tuor': 'tʰˈwɔɹ',
    'naor': 'nˈaʊɹ',
    'dar': 'tˈaɹ',
    'fur': 'fˈuɹ',
    'dunr': 'tˈwɚ',
    'langr': 'lˈɑɹ',
    'dair': 'tˈaɹ',
    'huar': 'xˈwaɹ',
    'yangr': 'jˈɑɹ',
}

def _chinese_character_to_pinyin(text: str) -> List[str]:
    pinyins = pypinyin.pinyin(text, style=pypinyin.Style.TONE3, heteronym=False, neutral_tone_with_five=True)
    pinyins_flat_list = [item for sublist in pinyins for item in sublist]
    return pinyins_flat_list


def _chinese_pinyin_to_phoneme(pinyin: str) -> str:
    segment = pinyin[:-1]
    tone = pinyin[-1]
    phoneme = PINYIN_DICT.get(segment, "")
    return phoneme + tone

def chinese_text_to_phonemes(text: str) -> str:
    tokenized_text = jieba.cut(text, HMM=False)
    tokenized_text = " ".join(tokenized_text)
    pinyined_text: List[str] = _chinese_character_to_pinyin(tokenized_text)

    results: List[str] = []
    for token in pinyined_text:
        if token[-1] in "12345":  # TODO transform to is_pinyin()
            pinyin_phonemes = _chinese_pinyin_to_phoneme(token)

            results += list(pinyin_phonemes)
        else:  # is ponctuation or other
            results += list(token)

    return ''.join(results)

if __name__ == "__main__":
    text = chinese_text_to_phonemes("我们都是中国人，我爱家乡")
    print(text)